### ISSUE TITLE
Absolute Imports

### ISSUE THREAD

**Issue by ahahn95** [postcss/postcss-import#391] opened 2019-03-27 19:32 UTC
Hi All,

I'm having trouble handling absolute imports. Before, everything was relative, but I have to move around tons of files, so having them find files regardless of their position in the directory is basically a requirement.

Should this problem be solved here? Am I setting something up incorrectly?

webpack config
```
resolve: {
        extensions: ['.jsx', '.js'],
        modules: [path.resolve(__dirname, 'src'), 'node_modules'],
        alias: {
            Robo: path.resolve(__dirname, 'src/RoboComponents')
        }
    },

...
(Module rules for PostCSS)
{
                        loader: 'postcss-loader',
                        options: {
                            ident: 'postcss',
                            plugins: () => [
                                postcssImport({
                                    path: [path.resolve(__dirname, 'src')]
                                }),
                                precss,
                                postcssPresetEnv({
                                    autoprefixer: {
                                        flexbox: 'no-2009'
                                    },
                                    stage: 3
                                }),
                                postCssVariables,
                                postcssFlexbugsFixes
                            ]
                        }
                    }
```
Import Example
```
@import '_variables/color/colors.css';
```

Directory Structure
```
.
package.json
webpack.base.config
src
   _variables
      color
         colors.css
      typography
         typography.css
 ...
```

**Comment by ar53n** [comment] 2019-06-24 14:03
Its really need i can't resolve absolute path 

`@import '/Users/my_comp/Documents/frontend/src/assets/styles/variables.css';`

**Comment by RyanZim** [comment] 2020-01-30 01:16
It's not clear to me what the issue is here; and I suspect given the time passed since this was opened, I couldn't be of much help here. Closing, happy to reopen if needed.

**Closed by RyanZim** 2020-01-30 01:16 UTC
