### ISSUE TITLE
Questions about resolve function

### ISSUE THREAD

**Issue by alinnert** [postcss/postcss-import#287] opened 2017-05-22 21:27 UTC
I just successfully integrated `postcss-import` (v10.0.0) in a [FuseBox](http://fuse-box.org) (v2.0.0) based project using the glob function you privide in `changelog.md`. But I've noticed a tiny difference. I'd like to point this out for people who are trying to achieve the same thing but I don't know if this is FuseBox related or not.
The problem was the following:

Example files:

~~~
C:\projects\my-project\src\styles\a.css
C:\projects\my-project\src\styles\b.css
C:\projects\my-project\src\main.css
C:\projects\my-project\package.json
C:\projects\my-project\fuse.js (FuseBox script that uses 'postcss-import', see below)
~~~

Content of `main.css`:

~~~css
@import "./styles/*.css";
~~~

Usage of `postcss-import` inside `fuse.js`:

~~~javascript
require('postcss-import')({
  resolve(id, base) { return glob.sync(path.join(base, id)); }
});
~~~

`base` contained the following: `C:\projects\my-project`
`id` contained the following: `./styles/*.css`

Now when I concat the path I get `C:\projects\my-project\styles\*.css` which is wrong because the `src` folder is missing.
It starts working after I change it to this:

~~~javascript
require('postcss-import')({
  resolve(id, base) { return glob.sync(path.join(base, 'src', id)); }
});
~~~

Now my questions:
- Is this just a very basic example and this would happen in any project or is this a FuseBox related problem?
- Shouldn't this use-case of the `resolve` function be mentioned in the `readme.md`? It's very hard to find in the `changelog.md`. Especially when more versions get released.
- While we're at it: It was a little hard to find out what `resolve` actually does. I needed to `console.log()` `base` and `id` to find the issue.
- The `readme.md` is still pointing out to `postcss-easy-import`. Isn't this obsolete by now?

Thanks for your help

**Comment by RyanZim** [comment] 2017-05-23 00:47
I'll answer your questions one-by-one.

1. This shouldn't happen in most projects. It has to do with the way the postcss runner (in this case FuseBox) sets the postcss `from` option.
1. There's various use-cases for it; PR welcome to improve the documentation.
1. See number 2 above
1. `postcss-easy-import`'s future is undecided. There's talk of adding glob, etc. to postcss-import, but nobody has presented a fully working implementation. We agree having multiple import plugins is sub-optimal, but we're undecided on how to fix the problem.

BTW, thanks for the clearly worded issue. I appreciate issues like this that contain all the info I need without making me guess at what the problem is. It makes our lives as maintainers easier. :smiley_cat:

**Comment by RyanZim** [comment] 2017-08-24 21:13
Closing for lack of action.

**Closed by RyanZim** 2017-08-24 21:13 UTC
