### ISSUE TITLE
undefined [undefined] warning for all imports after version 8.1.3

### ISSUE THREAD

**Issue by joedrummer8993** [postcss/postcss-import#277] opened 2017-04-20 21:58 UTC
I have one main css sheet that I import all of my other sheets to.  After version 8.1.3 every import is giving me a warning: "undefined [undefined]"

```
/* ------------------------------------ *\
    #Settings:
    Global variables, config switches
\* ------------------------------------ */
@import "settings.defaultBaseColors.css";
@import "settings.defaultInterfaceColors.css";
@import "settings.fonts.css";
@import "settings.sizes.css";

/* ------------------------------------ *\
    #Tools:
        Default mixins and functions
\* ------------------------------------ */
@import "tools.mixins.css";
@import "tools.mq-order.css";

/* ------------------------------------ *\
    #Generic:
        Ground-zero styles, resets
\* ------------------------------------ */
@import "generic.normalize.css";
@import "generic.customresets.css";

/* ------------------------------------ *\
    #Base:
        Type selector styles, no classes!
\* ------------------------------------ */
@import "base.all.css";

/* ------------------------------------ *\
    #Objects:
        Cosmetic free design patterns
\* ------------------------------------ */
@import "objects.images.css";
@import "objects.shapes.css";
@import "objects.navigation.css";
@import "objects.buttons.css";
@import "objects.dropdown.css";
@import "objects.media.css";
@import "objects.card.css";
@import "objects.cardList.css";
@import "objects.body.css";
@import "objects.grid.css";
@import "objects.list.css";
@import "objects.listRow.css";
@import "objects.dropdownList.css";
@import "objects.tableList.css";
@import "objects.listOfCards.css";
@import "objects.jquery.modal.min.css";

/* ------------------------------------ *\
    #Components:
        Designed components, chunks of UI
\* ------------------------------------ */
@import "components.background.css";
@import "components.betaBanner.css";
@import "components.buttons.css";
@import "components.form.css";
@import "components.toggleCheckbox.css";
@import "components.navSideBar.css";
@import "components.header.css";
@import "components.superHeader.css";
@import "components.footer.css";
@import "components.search.css";
@import "components.icons.css";
@import "components.text.css";
@import "components.links.css";
@import "components.navigation.css";
@import "components.account-nav.css";
@import "components.functionNav.css";
@import "components.breadcrumbs.css";
@import "components.heading.css";
@import "components.subHeading.css";
@import "components.tabs.css";
@import "components.categoryCard.css";
@import "components.categories.css";
@import "components.sideBar.css";
@import "components.filters.css";
@import "components.sort.css";
@import "components.productCard.css";
@import "components.product.css";
@import "components.productDetails.css";
@import "components.productPurchaseBox.css";
@import "components.productAttributes.css";
@import "components.productOptions.css";
@import "components.cartHeader.css";
@import "components.cartFooter.css";
@import "components.orderSummary.css";
@import "components.orderProductCard.css";
@import "components.cartLabels.css";
@import "components.projectCard.css";
@import "components.saveResponseCard.css";
@import "components.orderPreviewCard.css";
@import "components.listBody.css";
@import "components.listOptions.css";
@import "components.productListOptions.css";
@import "components.orderCard.css";
@import "components.shippingInfo.css";
@import "components.overviewList.css";
@import "components.personCard.css";
@import "components.documentationCard.css";
@import "components.documentationList.css";
@import "components.taxCertCard.css";
@import "components.rotator.css";
@import "components.datePicker.css";
@import "components.siteAlert.css";
@import "components.nuggets.css";
@import "components.modal.css";
@import "components.creditCard.css";
@import "components.noResults.css";
@import "components.checkout.css";
@import "components.priceFilter.css";
@import "components.errorPage.css";
@import "components.freightCharges.css";
@import "components.myOrders.css";
@import "components.notificationCard.css";
@import "components.myAccount.css";
@import "components.salesRepCard.css";
@import "components.myInfoCard.css";
@import "components.companyAccount.css";
@import "components.companyDivisions.css";
@import "components.companyUsers.css";
@import "components.listCard.css";
@import "components.listDetails.css";
@import "components.recentLists.css";
@import "components.phaseCard.css";
@import "components.quoteSummary.css";
@import "components.features.css";
@import "components.stream.css";
@import "components.pins.css";
/* ------------------------------------ *\
    #Trumps:
        Helpers and overrides, extensive use of !important
\* ------------------------------------ */
@import "trumps.all.css";
```

**Comment by RyanZim** [comment] 2017-04-20 22:06
@joedrummer8993 Just to clarify, this behavior persists with the latest v9.1.0? If so, could you provide a reproducible test case as a GH repo?

**Comment by michael-ciniawsky** [comment] 2017-04-21 09:14
@joedrummer8993 What build system are you currently using ? Gulp (`gulp-postcss`)?

**Comment by RyanZim** [comment] 2017-04-28 13:30
@joedrummer8993 ping?

**Comment by Nosherwan** [comment] 2017-05-10 00:32
I am having the same issue, although the css is imported and used the webpack build shows the warnings.
my imports are as follows:

```
@import '../../css/global.css';
@import '../../css/colors.css';
```

where as the warnings are:
```
common/react/shared/components/login/styles.css
undefined [undefined]
undefined [undefined]
```
versions I am using:
```
    webpack 2.4.1,
    "postcss": "^6.0.1",
    "postcss-cssnext": "^2.10.0",
    "postcss-focus": "1.0.0",
    "postcss-import": "^9.1.0",
    "postcss-loader": "1.3.3",
```

**Comment by RyanZim** [comment] 2017-05-10 13:28
I cannot investigate this issue without a reduced test case repo.

**Comment by Nosherwan** [comment] 2017-05-11 01:08
@RyanZim here is a test case repo for you :)
https://github.com/Nosherwan/post-css-import-warning

**Comment by RyanZim** [comment] 2017-05-11 15:22
@Nosherwan Thanks a million, will investigate as soon as I can.

**Comment by RyanZim** [comment] 2017-05-12 21:01
@michael-ciniawsky Will you take a look at this. I'm beginning to wonder if this is a webpack issue.

**Comment by michael-ciniawsky** [comment] 2017-05-13 18:14
@Nosherwan I took a quick look at this and the odd thing is that

### with `postcss-import`

![withimport](https://cloud.githubusercontent.com/assets/5419992/26027994/17ba1eea-3818-11e7-94b6-d7c8105977fe.png)

### without `postcss-import`

![withoutimport](https://cloud.githubusercontent.com/assets/5419992/26027995/2059c76c-3818-11e7-9eca-77aeda16de12.png)


but the warnings are unrelated to `postcss-import` itself and `postcss-reporter` works without regressions in conjunction to `postcss-loader` 

Something in `postcss-import`  seems to mess around with `result.warnings` but no clue where & why sry ¯\_(ツ)_/¯

**Comment by RyanZim** [comment] 2017-05-13 18:20
@michael-ciniawsky The reason for that is that the absence of postcss-import makes `--blue` undefined; if postcss-import was there, we wouldn't have these warnings.

**Comment by michael-ciniawsky** [comment] 2017-05-13 18:31
hmm... it could also be an display bug in `postcss-custom-properties` when `--blue` is defined and replaced by the plugin, but no fallback was set, the node where the warning is coming from might be 'dirty' at this point then. But it's 💯 not directly coming from `postcss-import` or `postcss-loader` 😛

**Comment by michael-ciniawsky** [comment] 2017-05-13 18:33
No idea how `postcss-custom-properties` handle/warns about all that cases. ¯\_(ツ)_/¯

**Comment by marzelin** [comment] 2017-06-01 11:35
Update `postcss-reporter` to version >=2.0.0.

Versions below 2 has a bug that causes all messages to be logged, but since `messages` also contain info about dependencies, you get those logged as well.
What makes this bug particularly enigmatic is that messages of `type: dependencies` does not contain two props that `postcss-reporter` relies on: `text` (info about what happened) and `node` info about which lone caused error which makes it log `undefined [undefined]`)

https://github.com/postcss/postcss-reporter/issues/30
https://github.com/TrySound/postcss-inline-svg/issues/32
https://github.com/postcss/postcss-reporter/compare/1.4.1...2.0.0#diff-7744650016d52918f79696c96d468795L32

**Comment by RyanZim** [comment] 2017-06-01 11:39
Closing as per @marzelin

**Closed by RyanZim** 2017-06-01 11:39 UTC
Labels: awaiting-reply

**Comment by wkentdag** [comment] 2017-10-13 00:45
I was getting `variable --blue is undefined and used without a fallback` type of errors when using `css-next` (uses this under the hood) - even though it was compiling correctly. I was able to get rid of the error by importing `postcss-import` as my first PostCSS plugin, before CSSNext. Maybe they're using an outdated version of `postcss-reporter`?
