### ISSUE TITLE
Incorrect nested import ordering

### ISSUE THREAD

**Issue by adam-h** [postcss/postcss-import#168] opened 2016-02-08 03:38 UTC
I just discovered this bug, where two imports that both import the same file can end up with the imported file out-of-order intermittently (due to parallel loading).

For example, if two separate files import `base.css`, in some cases the second file will process first and actually include it. Whereas the first file will not (due to de-duping) and then the result will be out-of-order and can affect the resulting applied styles (or variable definitions).

I have a full test case in my branch: https://github.com/adam-h/postcss-import/commit/569ea1ed4da1e7b84f1d190937a8341bbfac5b3b

Note how the first import is [delayed](https://github.com/adam-h/postcss-import/blob/569ea1ed4da1e7b84f1d190937a8341bbfac5b3b/test/order.js#L29-L31) so that the second will always process first (removing the randomness of occurance due to the filesystem).

**Comment by jedmao** [comment] 2016-02-08 03:41
Can you create a PR with a breaking test?

**Comment by adam-h** [comment] 2016-02-08 03:51
Done :) https://github.com/postcss/postcss-import/pull/169

**Comment by tarikihm** [comment] 2016-03-01 19:41
What is the status on this issue? I am also affected by it.

**Comment by MoOx** [comment] 2016-03-02 13:47
The status of an opened issue is: the issue is still open, so not fixed.

**Comment by tarikihm** [comment] 2016-03-09 21:34
No worries, does anybody has a workaround for this issue? Perhaps disabling de-duping?

**Comment by tarikihm** [comment] 2016-03-30 15:58
For anyone looking at this issue, temporary fix is to set `skipDuplicates: false`.

**Comment by simplesmiler** [comment] 2016-04-01 10:35
`skipDuplicates: false` does not solve the issue for me.

**Comment by paulyoung** [comment] 2016-05-18 18:37
I believe I am also experiencing this issue. I was about to post the following which sounds like https://github.com/postcss/postcss-simple-vars/issues/42 and looks a lot like #169.

Doing the following causes intermittent `TypeError: Cannot read property 'toString' of undefined` errors.

_a.css_
```css
@import 'some-module/variables.css';
// use variables from variables.css
```

_b.css_
```css
@import 'some-module/variables.css';
// use variables from variables.css
```

_index.css_
```css
@import './a.css';
@import './b.css';
```

As a result we've had to resort to:

_a.css_
```css
/*@import 'some-module/variables.css';*/
// use variables from variables.css
```

_b.css_
```css
/*@import 'some-module/variables.css';*/
// use variables from variables.css
```

_index.css_
```css
@import 'some-module/variables.css';
@import './a.css';
@import './b.css';
```

**Comment by MoOx** [comment] 2016-05-18 19:13
Please use v7 while it's resolved.

**Comment by paulyoung** [comment] 2016-05-18 19:42
That appears to work. Thanks!

**Comment by MoOx** [comment] 2016-11-02 16:23
@RyanZim maybe everything is a mess because of this line https://github.com/postcss/postcss-import/blob/6bbcdbd9a6b52ad45bd1ab4853b98b68719c9ca5/index.js#L166

Promise.all might resolve without taking the correct expected order (really not sure about that, but that may be a clue)

**Comment by RyanZim** [comment] 2016-11-02 18:04
@MoOx Did a little fooling, couldn't figure it out. Mind elaborating a bit?

---

(Un)related question: What does `resolveImportId()` actually do? It returns a promise, but the final `then` in the promise chain doesn't return anything. I assume it mutates an object somewhere, but what object does it mutate?

**Comment by MoOx** [comment] 2016-11-02 20:22
As I said before, I am not the author of this code base, and the author decided to ignore this project for some reasons (that's why I talked about reverting to v7, which is a codebase I know). Anyway I will try to give you some pointers.

At the end, resolveImportId() mutate the initial passed statement (called stmt) childrens. The naming of "result" inside the function is a bit confusing since the parent block level also have a "result" variable.

I merged a failing test into master, so know you can do the following:

- `ava test/order.js` to trigger the failure and iterate with this.

**Comment by RyanZim** [comment] 2016-11-02 22:32
@MoOx Progress! :tada: I think I am getting closer to the issue.

**Comment by RyanZim** [comment] 2016-11-02 23:33
@MoOx @ai I have found the issue and made a fix, however, I broke the `should apply plugins to root` test at https://github.com/postcss/postcss-import/blob/master/test/plugins.js in the process. I suspect the test depended on the the old incorrect behavior. Will investigate tomorrow.

@MoOx If that test is depending on incorrect behavior, please tell me/submit a PR.

**Comment by RyanZim** [comment] 2016-11-02 23:55
Thought I would leave this for tomorrow; I was so engrossed, I had to fix it tonight! The test was faulty.

PR done: https://github.com/postcss/postcss-import/pull/236. :tada:

**Closed** 2016-11-03 14:42 UTC
